# Generated by Django 2.2a1 on 2019-04-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20190412_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pictures'),
        ),
    ]
