# Generated by Django 2.2a1 on 2019-04-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_company_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pictures'),
        ),
    ]
