# Generated by Django 2.2a1 on 2019-04-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20190412_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='resume',
            field=models.ImageField(blank=True, upload_to='jobseeker_resume'),
        ),
    ]
