# Generated by Django 2.2a1 on 2019-04-13 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_jobseeker_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseeker',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='last_name',
        ),
    ]
