# Generated by Django 2.2a1 on 2019-04-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20190413_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='city',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='country',
            field=models.CharField(default='empty', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='zipcode',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
