# Generated by Django 2.2a1 on 2019-04-13 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20190413_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseeker',
            old_name='country',
            new_name='state',
        ),
    ]
