# Generated by Django 2.2a1 on 2019-04-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_auto_20190413_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='job',
            field=models.ManyToManyField(default=0, to='job.Jobfield'),
        ),
    ]
